import deduruOya1 from './assets/deduruoya1.jpg';
import deduruOya2 from './assets/deduruoya2.jpg';
import deduruOya3 from './assets/deduruoya3.jpg';
import deduruOya4 from './assets/deduruoya4.jpg';
import deduruOya5 from './assets/deduruoya5.jpg';
import deduruOya6 from './assets/deduruoya6.jpg';
import deduruOya7 from './assets/deduruoya7.jpg';
import deduruOya8 from './assets/deduruoya8.jpg';
import deduruOya9 from './assets/deduruoya9.jpg';
import deduruOya10 from './assets/deduruoya10.jpg';
import deduruOya11 from './assets/deduruoya11.jpg';
import kumbalgamuwa1 from './assets/kumbalgamuwa1.jpg';
import kumbalgamuwa2 from './assets/kumbalgamuwa3.jpg';
import kumbalgamuwa3 from './assets/kumbalgamuwa5.jpg';
import kumbalgamuwa4 from './assets/kum.jpeg';
import sle1 from './assets/sethsiripaya.jpg';
import biomed1 from './assets/biomed1.jpg';
import biomeed2 from './assets/biomeed2.jpg';

export const cards = [
  {
    id: 1,
    title: "Deduru Oya",
    desc: "Mini Hydro Power Plant",
    img: "https://via.placeholder.com/300x200?text=Deduru+Oya",
  },
  {
    id: 2,
    title: "Kumbalgamuwa",
    desc: "Mini Hydro Plant",
    img: "https://via.placeholder.com/300x200?text=Kumbalgamuwa",
  },
  {
    id: 3,
    title: "Biomed",
    desc: "Mini Hydro Plant",
    img: "https://via.placeholder.com/300x200?text=Biomed",
  },
  {
    id: 4,
    title: "MEMP",
    desc: "Meter Enclosure Manufacturing Plant",
    img: "https://via.placeholder.com/300x200?text=MEMP",
  },
  {
    id: 5,
    title: "SCALP",
    desc: "Aluminium Recycling",
    img: "https://via.placeholder.com/300x200?text=SCALP",
  },
  {
    id: 6,
    title: "Solar",
    desc: "Solar Power Development",
    img: "https://via.placeholder.com/300x200?text=Solar",
  },
  {
    id: 7,
    title: "Upper Samanala",
    desc: "Upper Samanala",
    img: "https://via.placeholder.com/300x200?text=Upper+Samanala",
  },
  {
    id: 8,
    title: "Weganthale",
    desc: "Weganthale",
    img: "https://images.pexels.com/photos/15032623/pexels-photo-15032623.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 9,
    title: "Head Office",
    desc: "Administrative Headquarters",
    img: "https://via.placeholder.com/300x200?text=Head+Office",
  },
];

export const powerPlants = [
  {
    id: 1,
    title: "Head Office",
    desc: "Administrative Headquarters",
    plantType: "HeadOffice",
    companyName: "Sri Lanka Energies Pvt Ltd",
    function: "Administrative and Management",
    departments: "HR, Finance, Operations, IT, Engineering, Project Management",
    established: "2012",
    parentCompany: "Ceylon Electricity Board (CEB)",
    address: "11th Floor, Sethsiri Paya Stage II, Battaramulla, Sri Lanka",
    location: "Battaramulla, Sri Lanka",
    coordinates: { lat: 6.9271, lng: 79.8612 },
    commissioningDate: "2012",
    operator: "Sri Lanka Energies Pvt Ltd",
    description: "The head office oversees all administrative and strategic operations, coordinating activities across all plants without direct involvement in power generation or production. As a wholly owned subsidiary of the Ceylon Electricity Board, it focuses on constructing transmission lines, grid substations, and managing subsidiaries in the energy sector.",
    images: [sle1],
    keyFunctions: "Policy making, financial management, human resources, project oversight, renewable energy development",
    vision: "To be a leading provider of sustainable energy solutions in Sri Lanka.",
    mission: "To deliver efficient, innovative, and eco-friendly energy services through strategic management and collaboration.",
    subsidiaries: "Sri Lanka Energies HR (Private) Ltd, and others involved in manpower and specialized projects.",
    status: "Administrative",
  },
  {
    id: 2,
    title: "Deduru Oya",
    desc: "Mini Hydro Power Plant",
    plantType: "Hydro",
    type: "Mini Hydro",
    capacity: "1.3 MW",
    location: "Sri Lanka",
    coordinates: { lat: 7.71719, lng: 80.27975 },
    commissioningDate: "2021",
    
    description: "A small-scale hydroelectric plant harnessing the Deduru Oya river flow to generate clean energy for the local region.",
    images: [
      deduruOya1,
      deduruOya2,
      deduruOya4,
      deduruOya5,
      deduruOya6,
      deduruOya7,
      deduruOya8,
      deduruOya9,
      deduruOya10,
      deduruOya11,
    ],
    specifications: {
      turbineType: "Kaplan",
      head: "15.6m",
      flowRate: "9.5 m³/s",
    },
    status: "Operational",
  },
  {
    id: 3,
    title: "Kumbalgamuwa",
    desc: "Mini Hydro Plant",
    plantType: "Hydro",
    type: "Mini Hydro",
    capacity: "1.3 MW",
    location: "Sri Lanka",
    coordinates: { lat: 6.8, lng: 80.2 },
    commissioningDate: "2017",
    operator: "Green Energy Lanka",
    description: "Compact hydroelectric facility providing renewable energy to rural communities.",
    images: [kumbalgamuwa1, kumbalgamuwa2, kumbalgamuwa3, kumbalgamuwa4],
    specifications: {
      turbineType: "Francis",
      head: "40m",
      flowRate: "3.8 m³/s",
    },
    status: "Operational",
  },
  {
    id: 4,
    title: "Biomed",
    desc: "Mini Hydro Plant",
    plantType: "Hydro",
    type: "Mini Hydro",
    capacity: "0.9MW",
    location: "Sri Lanka",
    coordinates: { lat: 6.8, lng: 80.2 },
    commissioningDate: "2023",
    operator: "BioEnergy Solutions",
    description: "Eco-friendly hydro plant with minimal environmental impact.",
    images: [biomed1, biomeed2, "http://124.43.4.17:3000/assets/Biomed_6-B1tHqz3W.jpeg"],
    specifications: {
      turbineType: "Francis",
      head: "40m",
      flowRate: "2a m³/s",
    },
    status: "Operational",
  },
  {
    id: 5,
    title: "MEMP",
    desc: "Meter Enclosure Manufacturing Plant",
    plantType: "Production",
    type: "Meter Enclosure Manufacturing",
    capacity: "Annual: 300,000 units",
    location: "Galigamuwa Industrial Zone, Kegalle, Sri Lanka",
    coordinates: { lat: 7.236, lng: 80.312 },
    commissioningDate: "2015",
    operator: "Sri Lanka Energies Pvt Ltd",
    description: "A specialized manufacturing facility producing high-quality polycarbonate meter enclosures to meet the needs of Ceylon Electricity Board (CEB) and Lanka Electricity Company (LECO). The plant features advanced injection molding technology for efficient and sustainable production.",
    images: ["http://124.43.4.17:3000/assets/memmp-background-DvTLsyFW.jpg"],
    productionType: "Polycarbonate Meter Enclosures",
    dailyProduction: "1,000 units",
    weeklyProduction: "6,000 units",
    monthlyProduction: "25,000 units",
    output: "300,000 units annually",
    machinery: "Injection molding machines, assembly lines, quality control systems",
    status: "Operational",
  },
  {
    id: 6,
    title: "SCALP",
    desc: "Aluminium Recycling",
    plantType: "Recycling",
    type: "Recycling",
    capacity: "0 tons/month",
    location: "Sri Lanka",
    coordinates: { lat: 6.0, lng: 80.2 },
    commissioningDate: "2025",
    description: "Specialized facility for recycling aluminum, contributing to sustainable material use.",
    images: ["http://124.43.4.17:3000/uploads/1751804813739.jpg"],
    productionType: "Aluminum Recycling",
    output: "0 tons of recycled aluminum per month",
    machinery: "Melting furnaces, Shredders",
    status: "Not Operational",
  },
  {
    id: 7,
    title: "Solar",
    desc: "Solar Power Development",
    plantType: "Solar",
    type: "Solar",
    capacity: "15 MW",
    location: "Sri Lanka",
    coordinates: { lat: 7.1, lng: 80.0 },
    commissioningDate: "2021",
    description: "Medium-scale solar farm with tracking system for increased efficiency.",
    images: ["https://img.freepik.com/premium-photo/aerial-view-large-sustainable-electrical-power-plant-with-many-rows-solar-photovoltaic-panels_127089-18663.jpg"],
    specifications: {
      panelType: "Monocrystalline",
      trackingSystem: "Single-axis",
      efficiency: "19%",
    },
    status: "Operational",
  },
  // {
  //   id: 8,
  //   title: "Upper Samanala",
  //   desc: "Upper Samanala",
  //   plantType: "Hydro",
  //   type: "Hydroelectric",
  //   capacity: "120 MW",
  //   location: "Sri Lanka",
  //   coordinates: { lat: 6.7, lng: 80.8 },
  //   commissioningDate: "2012",
  //   description: "Large hydroelectric dam with significant power generation capacity.",
  //   images: [
  //     "https://via.placeholder.com/300x200?text=Upper+Samanala",
  //     "https://example.com/hydro7.jpg",
  //   ],
  //   specifications: {
  //     turbineType: "Francis",
  //     head: "150m",
  //     reservoirCapacity: "50 million m³",
  //   },
  //   status: "Operational",
  // },
  // {
  //   id: 9,
  //   title: "Weganthale",
  //   desc: "Weganthale",
  //   plantType: "Thermal",
  //   type: "Thermal",
  //   capacity: "30 MW",
  //   location: "Sri Lanka",
  //   coordinates: { lat: 7.3, lng: 80.6 },
  //   commissioningDate: "2016",
  //   operator: "Lanka Power Gen",
  //   description: "Combined cycle power plant with improved efficiency.",
  //   images: [
  //     "https://images.pexels.com/photos/15032623/pexels-photo-15032623.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  //   ],
  //   specifications: {
  //     fuelType: "Natural Gas",
  //     efficiency: "45%",
  //     combinedCycle: true,
  //   },
  //   status: "Operational",
  // },
];

export const projects = [
  {
    id: 1,
    img: "https://via.placeholder.com/300x200?text=Kumbalgamuwa",
    pp: "",
    cat: "Kumbalgamuwa",
    username: "Mr Chandu",
  },
  {
    id: 2,
    img: "https://via.placeholder.com/300x200?text=Upper+Samanala",
    pp: "",
    cat: "Kumbalgamuwa",
    username: "",
  },
  {
    id: 3,
    img: "https://via.placeholder.com/300x200?text=SCALP",
    pp: "",
    cat: "",
    username: "Emmett Potter",
  },
  {
    id: 4,
    img: "https://via.placeholder.com/300x200?text=Biomed",
    pp: "",
    cat: "Biomed",
    username: "Mr Gayantha",
  },
  {
    id: 5,
    img: "https://via.placeholder.com/300x200?text=Deduru+Oya",
    pp: "",
    cat: "Deduru Oya",
    username: "Mr Hemal",
  },
  {
    id: 6,
    img: "https://via.placeholder.com/300x200?text=SCALP",
    pp: "",
    cat: "",
    username: "",
  },
  {
    id: 7,
    img: "https://via.placeholder.com/300x200?text=Biomed",
    pp: "",
    cat: " ",
    username: " ",
  },
  {
    id: 8,
    img: "https://via.placeholder.com/300x200?text=Kumbalgamuwa",
    pp: "",
    cat: " ",
    username: " ",
  },
];

export const gigs = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/580151/pexels-photo-580151.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/720598/pexels-photo-720598.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create ai art character from your images and prompts",
    price: 59,
    star: 5,
    username: "Anna Bell",
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/4145190/pexels-photo-4145190.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1036627/pexels-photo-1036627.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create ultra high quality character art with ai",
    price: 79,
    star: 5,
    username: "Lannie Coleman",
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/8797307/pexels-photo-8797307.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1062280/pexels-photo-1062280.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will creating unique ai generated artworks mid journey ai artist",
    price: 112,
    star: 5,
    username: "Carol Steve",
  },
  {
    id: 4,
    img: "https://images.pexels.com/photos/5708069/pexels-photo-5708069.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create custom ai generated artwork using your photos",
    price: 99,
    star: 4,
    username: "Don Weber",
  },
  {
    id: 5,
    img: "https://images.pexels.com/photos/5699456/pexels-photo-5699456.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1771383/pexels-photo-1771383.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will recreate your dreams in high quality pictures",
    price: 59,
    star: 5,
    username: "Audrey Richards",
  },
  {
    id: 6,
    img: "https://images.pexels.com/photos/8100784/pexels-photo-8100784.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/715546/pexels-photo-715546.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create ai digital art illustration hyper realistic painting",
    price: 79,
    star: 4,
    username: "Walton Shepard ",
  },
  {
    id: 7,
    img: "https://images.pexels.com/photos/6039245/pexels-photo-6039245.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/720606/pexels-photo-720606.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will generate images with your prompts using ai dalle",
    price: 89,
    star: 5,
    username: "Waverly Schaefer",
  },
  {
    id: 8,
    img: "https://images.pexels.com/photos/5490778/pexels-photo-5490778.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1699159/pexels-photo-1699159.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create custom art using midjourney generator",
    price: 110,
    star: 4,
    username: "Wilton Hunt",
  },
];